/**
 * Supported data types for the entire application
 * Used for column mapping, validation, and data processing across all modules
 */
export type SupportedDataType = 'string' | 'integer' | 'float' | 'date';

/**
 * System fields for all database entities
 * Standard fields that are automatically managed by the system
 *
 * Usage:
 * - Apply to all database entities (Company, Invoice, Period, etc.)
 * - id: Unique identifier (auto-generated by SQLite AUTOINCREMENT)
 * - createdAt/updatedAt: Audit trail timestamps (auto-managed)
 * - Required for data integrity and audit trail
 */
export interface SystemFields {
  /** Unique identifier (auto-generated by SQLite INTEGER PRIMARY KEY AUTOINCREMENT) */
  id: number;

  /** Record creation timestamp */
  createdAt?: Date;

  /** Last update timestamp */
  updatedAt?: Date;
}
